### ISSUE TITLE
FBP definition

### ISSUE THREAD

**Issue by trustmaster** [flowbased/flow-based.org#2]
@oleksandr, you've mentioned it several times on the mailing list that you've got clear perception of FBP's place among other dataflow systems after reading Matt Carkci's "Dataflow and Reactive Programming Systems" book. Could you probably give it a try and write the Definition page of this wiki when you have time, please?

**Comment by oleksandr** [comment]
Sure. I will write a little overview based on that book over this weekend.

**Comment by trustmaster** [comment]
OK, i gave it a try. Corrections and additions are welcomed.

**Comment by trustmaster** [comment]
@alfa256, thanks for helping with this!  Your corrections fit the bill.

**Comment by oleksandr** [comment]
@trustmaster Sorry for skipping this one, heavy project work load. It would be nice also to add couple of sentences about connection joins and splits: what is allowed and what not. In some data flow systems the joins/splits should be separate components (similar how a IIP is modelled by a sender/oneshot component). But in classical FBP we can have joins (several output ports connected to a single input port, IPs are "merged" in the natural arrival order) but we cannot connect same output port to several input ports because IPs are unique. I believe this an important part when it comes to implementation.

@jpaulm What do you think?

**Comment by trustmaster** [comment]
@oleksandr, I think @jpaulm agrees with the importance of this rule because he defined it in first place :smiley: 

I added it to the characteristics list: https://github.com/flowbased/flowbased.org/wiki/Definition/_compare/0c6d9ad%5E...0c6d9ad

**Comment by oleksandr** [comment]
Cool. Thanks :-)

**Comment by jpaulm** [comment]
Yes, absolutely!  I like the way the new characteristic is worded.
