### ISSUE TITLE
Why doesn't index.html display in formatted form?

### ISSUE THREAD

**Issue by jpaulm** [flowbased/flow-based.org#27]
When I click on https://github.com/flowbased/flowbased.org/blob/gh-pages/index.html , I just see raw html - anyone know why this?  I am running it on Firefox, Win 7.

TIA

Paul M.

**Comment by jpaulm** [comment]
For some reason I had to download the project first, then open index.html with Firefox...  Looks nice - but it doesn't say anything about flowbased.org!  It's all about gh-pages!  

Is anyone working on flowbased.org?  I asked for the status 2 weeks ago (#26), and no response so far!

@jonnor @bergie @oleksandr @chadrik  Anyone...?!

**Comment by rhalff** [comment]
Seems like it just contains a default page, to get the contents of the wiki you can clone:

  https://github.com/flowbased/flowbased.org.wiki.git

Which is just a set of markdown files.

These will have to be generated into html pages and then pushed to:

  https://github.com/flowbased/flowbased.org.git

From the look of it you can just force push to the gh-pages branch, the only thing you need to retain is the CNAME file which will cause the site to be available at http://flowbased.org instead of the default location which is http://flowbased.github.io/flowbased.org

When you push to a `gh-pages` branch on github it will automatically be made available / served.

There is no standard way of generating markdown files to html pages, one option seems to be:

  https://github.com/bebraw/ghw

When ghw is used the pages look something like this:

![ghw](https://cloud.githubusercontent.com/assets/274358/16363599/8862a702-3bcf-11e6-9596-40fa49c15e5c.png)

However, this being about flowbased and all, perhaps it's a challenge to generate a site from these markdown files by using FBP?

NoFlo has components to do it, but JavaFBP should be capable also if you have a markdown component and a template component to produce the desired html.

**Comment by jonnor** [comment]
Github has built-in support for Jekyll for gh-pages branch, for building HTML from Markdown.

**Comment by jonnor** [comment]
I made the https://flowbased.org website a simple static frontpage, which then links out to wiki/github/mailinglist.
