### ISSUE TITLE
Input Ports (in Concepts)

### ISSUE THREAD

**Issue by jpaulm** [flowbased/flow-based.org#9]
> Other features like obtaining the buffer load or which indexes have incoming packets in the case of array ports are desirable for simplifying the design and implementation of some components.

This is more of a comment than a question, so I will use the enhancement tag!

a) We have never needed the cited functions (but maybe NoFlo does)

b) The load balancer I built has one "secret" function to check the number of IPs in its _downstream_ connection

c) Input Ports should mention suspension, to parallel the way that Output Ports does...

**Comment by alfa256** [comment]
Something like peeking into a port to see if it has packets awaiting or
getting indexes in an array port with packets can be helpful, and there
aren't any harmful side effects of doing such a thing. It's mostly a
comment, not a requirement of FBP.
I implemented some helper functions for ports on my implementation of FBP
so that's why I mention it, One was Peek to check if a port has incoming
packets and another one is Peek_Timeout to peek for a number of
milliseconds. It simplifies tasks like for example a process that converts
dollars to euros and it peeks for a new exchange rate on a port before
doing the conversion. Otherwise implementing it would be more complicated,
with either a process sending the previous packet with every request or
using brackets, etc.
I will add the bit about blocking reads.

2014-06-17 22:58 GMT-03:00 jpaulm notifications@github.com:

**Comment by bergie** [comment]
@alfa256 NoFlo supports "peeking" via the `inport.contains()` method which returns a boolean telling whether there are IPs in the buffer or not.

However, there are many transport mechanisms like message queues that might be useful for FBP implementations, but might not be able to support peeking. For example, RabbitMQ does not. Therefore it wouldn't be a good idea to require this feature in the spec.

**Comment by oleksandr** [comment]
:+1: in support of @bergie point. We use ZMQ and Mosquitto for connections implementation and it's impossible to "peek". It's a nice feature but rather rare among queue implementations.

**Comment by alfa256** [comment]
I did not state it as a requirement but as a "nice to have". We are making
a condensed explanation of local FBP, as distributed implementations will
always have to make some trade offs, so in that light we should point to
the advantages of having more control over buffers and the graph and its
possibilities.

2014-06-18 11:51 GMT-03:00 Oleksandr Lobunets notifications@github.com:

**Comment by jpaulm** [comment]
And this one too!  Feel free to reopen any one that needs it!
